### ISSUE TITLE
aicsimageio in napari-serialcellpose is only able to read png, not tif

### ISSUE THREAD

**Issue by centaraa** [guiwitz/napari-serialcellpose#10]
As recommended in a new environment, I installed napari-serialcellpose. 
Unfortunately, here aicsimageio is not able to open / read tif files with channels xyz=1 and t=1. 

In a different environment, aicsimageio is able to read in tif files.

PNG images in folder are displayed correctly and custom cellpose model run without problem...
What could be the issue?

Traceback shows this:

`TypeError: unexpected keyword argument: is_mmstack`

**Comment by guiwitz** [comment]
I think you are encountering [this bug](https://github.com/AllenCellModeling/aicsimageio/issues/495) in the tifffile package. Can you check which version of tifffile you have? And if it's still a 2022.X.X version try to update it with ```pip install tifffile==2023.9.26```.

**Comment by centaraa** [comment]
Dear @guiwitz , thank you! 
Although it only worked for me with the version of tifffile==2023.7.10, I was able to solve this issue.
